include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  errors:
    one_member_abstracts: ignore
  exclude:
    - "*.g.dart"
    - "**/*.g.dart"
    - "lib/data/models/generated/**"

linter:
  rules:
    public_member_api_docs: true
    lines_longer_than_80_chars: false
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
    sort_child_properties_last: true
