targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
          include_if_null: false
          create_to_json: true
      source_gen|combining_builder:    
        options:  
          build_extensions:
            '^lib/data/models/{{}}.dart': 'lib/data/models/generated/{{}}.g.dart'
          
          
