name: musicify
description: spotify control
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  convert: ^3.1.2
  crypto: ^3.0.6
  dio: ^5.8.0+1
  envied: ^1.1.0
  equatable: ^2.0.7
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  fpdart: ^1.1.1     
  get_it: ^8.0.3  
  go_router: ^14.7.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  musicify_widgets:
    path: modules/musicify_widgets
  realm: ^20.0.1
  shimmer: ^3.0.0  
  talker_dio_logger: ^4.7.1  
  url_launcher: ^6.3.1
  


  


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  envied_generator: ^1.1.0
  flutter_launcher_icons: "^0.14.3"

  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha: true
  image_path: "assets/icon/icon.png"  
  
  
  
  

flutter:
  uses-material-design: true
  generate: true
